# Generated by Django 3.2.11 on 2024-10-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp_create', models.DateTimeField()),
                ('number_of_user', models.IntegerField()),
            ],
            options={
                'db_table': 'session_data',
            },
        ),
    ]
