# Generated by Django 3.2.11 on 2024-08-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
